package modules

import (
	_ "github.com/aydocs/fang/modules/0day"
	_ "github.com/aydocs/fang/modules/adcs"
	_ "github.com/aydocs/fang/modules/android"
	_ "github.com/aydocs/fang/modules/arsenal"
	_ "github.com/aydocs/fang/modules/bluetooth"
	_ "github.com/aydocs/fang/modules/browser"
	_ "github.com/aydocs/fang/modules/central"
	_ "github.com/aydocs/fang/modules/cicd"
	_ "github.com/aydocs/fang/modules/cloud"
	_ "github.com/aydocs/fang/modules/cloudkill"
	_ "github.com/aydocs/fang/modules/cmdi"
	_ "github.com/aydocs/fang/modules/cors"
	_ "github.com/aydocs/fang/modules/crlf"
	_ "github.com/aydocs/fang/modules/dataphantom"
	_ "github.com/aydocs/fang/modules/deser"
	_ "github.com/aydocs/fang/modules/devnull"
	_ "github.com/aydocs/fang/modules/docker"
	_ "github.com/aydocs/fang/modules/endgame"
	_ "github.com/aydocs/fang/modules/evasion"
	_ "github.com/aydocs/fang/modules/exchange"
	_ "github.com/aydocs/fang/modules/git"
	_ "github.com/aydocs/fang/modules/graphql"
	_ "github.com/aydocs/fang/modules/headers"
	_ "github.com/aydocs/fang/modules/helm"
	_ "github.com/aydocs/fang/modules/idpwn"
	_ "github.com/aydocs/fang/modules/inject"
	_ "github.com/aydocs/fang/modules/ios"
	_ "github.com/aydocs/fang/modules/iot"
	_ "github.com/aydocs/fang/modules/k8s"
	_ "github.com/aydocs/fang/modules/kerberos"
	_ "github.com/aydocs/fang/modules/ldap"
	_ "github.com/aydocs/fang/modules/lfi"
	_ "github.com/aydocs/fang/modules/malware"
	_ "github.com/aydocs/fang/modules/method"
	_ "github.com/aydocs/fang/modules/nosqli"
	_ "github.com/aydocs/fang/modules/npm"
	_ "github.com/aydocs/fang/modules/ntlm"
	_ "github.com/aydocs/fang/modules/oidc"
	_ "github.com/aydocs/fang/modules/payment"
	_ "github.com/aydocs/fang/modules/phish"
	_ "github.com/aydocs/fang/modules/proto"
	_ "github.com/aydocs/fang/modules/race"
	_ "github.com/aydocs/fang/modules/recon"
	_ "github.com/aydocs/fang/modules/redirect"
	_ "github.com/aydocs/fang/modules/rest"
	_ "github.com/aydocs/fang/modules/reverse"
	_ "github.com/aydocs/fang/modules/rfid"
	_ "github.com/aydocs/fang/modules/saml"
	_ "github.com/aydocs/fang/modules/sbom"
	_ "github.com/aydocs/fang/modules/sdr"
	_ "github.com/aydocs/fang/modules/serverless"
	_ "github.com/aydocs/fang/modules/shadow"
	_ "github.com/aydocs/fang/modules/smb"
	_ "github.com/aydocs/fang/modules/smuggler"
	_ "github.com/aydocs/fang/modules/soap"
	_ "github.com/aydocs/fang/modules/spectre"
	_ "github.com/aydocs/fang/modules/sqli"
	_ "github.com/aydocs/fang/modules/ssrf"
	_ "github.com/aydocs/fang/modules/ssti"
	_ "github.com/aydocs/fang/modules/strike"
	_ "github.com/aydocs/fang/modules/terraform"
	_ "github.com/aydocs/fang/modules/vpn"
	_ "github.com/aydocs/fang/modules/websocket"
	_ "github.com/aydocs/fang/modules/wifi"
	_ "github.com/aydocs/fang/modules/xpath"
	_ "github.com/aydocs/fang/modules/xss"
	_ "github.com/aydocs/fang/modules/xxe"

	"github.com/aydocs/fang/internal/engine"
)

func init() {
	_ = engine.GetRegistry()
}
