// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelScan() {
  return window['go']['main']['App']['CancelScan']();
}

export function CreateSchedule(arg1) {
  return window['go']['main']['App']['CreateSchedule'](arg1);
}

export function CreateTarget(arg1) {
  return window['go']['main']['App']['CreateTarget'](arg1);
}

export function DeleteNotification(arg1) {
  return window['go']['main']['App']['DeleteNotification'](arg1);
}

export function DeleteSchedule(arg1) {
  return window['go']['main']['App']['DeleteSchedule'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['main']['App']['DeleteTarget'](arg1);
}

export function GenerateReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2);
}

export function GetActiveScan() {
  return window['go']['main']['App']['GetActiveScan']();
}

export function GetAllFindings(arg1, arg2) {
  return window['go']['main']['App']['GetAllFindings'](arg1, arg2);
}

export function GetModuleStats() {
  return window['go']['main']['App']['GetModuleStats']();
}

export function GetNotifications() {
  return window['go']['main']['App']['GetNotifications']();
}

export function GetReportDir() {
  return window['go']['main']['App']['GetReportDir']();
}

export function GetScan(arg1) {
  return window['go']['main']['App']['GetScan'](arg1);
}

export function GetScanFindings(arg1) {
  return window['go']['main']['App']['GetScanFindings'](arg1);
}

export function GetScans() {
  return window['go']['main']['App']['GetScans']();
}

export function GetSchedules() {
  return window['go']['main']['App']['GetSchedules']();
}

export function GetSeverityStats() {
  return window['go']['main']['App']['GetSeverityStats']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTargets() {
  return window['go']['main']['App']['GetTargets']();
}

export function ListModules() {
  return window['go']['main']['App']['ListModules']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function RunScan(arg1, arg2) {
  return window['go']['main']['App']['RunScan'](arg1, arg2);
}

export function RunScanAsync(arg1, arg2) {
  return window['go']['main']['App']['RunScanAsync'](arg1, arg2);
}
