// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {db} from '../models';

export function CancelScan():Promise<void>;

export function CreateSchedule(arg1:main.ScheduleInput):Promise<string>;

export function CreateTarget(arg1:string):Promise<string>;

export function DeleteNotification(arg1:string):Promise<void>;

export function DeleteSchedule(arg1:string):Promise<void>;

export function DeleteTarget(arg1:string):Promise<void>;

export function GenerateReport(arg1:string,arg2:string):Promise<string>;

export function GetActiveScan():Promise<string>;

export function GetAllFindings(arg1:number,arg2:number):Promise<Array<db.FindingRow>>;

export function GetModuleStats():Promise<Array<db.ModuleStat>>;

export function GetNotifications():Promise<Array<db.NotificationRow>>;

export function GetReportDir():Promise<string>;

export function GetScan(arg1:string):Promise<db.ScanRow>;

export function GetScanFindings(arg1:string):Promise<Array<db.FindingRow>>;

export function GetScans():Promise<Array<db.ScanRow>>;

export function GetSchedules():Promise<Array<db.ScheduleRow>>;

export function GetSeverityStats():Promise<Array<db.SeverityStat>>;

export function GetStats():Promise<main.ScanStats>;

export function GetTargets():Promise<Array<db.TargetRow>>;

export function ListModules():Promise<Array<main.ModuleInfo>>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function RunScan(arg1:string,arg2:Array<string>):Promise<string>;

export function RunScanAsync(arg1:string,arg2:Array<string>):Promise<string>;
